modLoader="javafml"
loaderVersion="[20,)"
license="MIT License"
logoFile="pack.png"
logoBlur=false

[[mods]]
modId="jdi_origins"
displayName="JDi Origins"
version="0.6_alpha_p"
description='''
A Collection Of Origins (3 Currently) Based Off Of Characters Made By NicholasJDi.
'''
[[dependencies.jdi_origins]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.0,1.20.1]"
    ordering="NONE"
    side="BOTH"
[[dependencies.jdi_origins]]
    modId="origins"
    mandatory=true
    versionRange="[0.1.0,)"
    ordering="NONE"
    side="BOTH"
